program.anzu
src/anzu.m.cpp
src/op_codes.cpp
src/op_codes.hpp
src/stack_frame.cpp

* Add multiplication '*', division '/', and modulo '%' for integers.
* Add 'and', 'or', '<', '<=', '>', '>=' for booleans.
* Remove `let <name> <value>` as it doesn't work well for storing new calculations, and also requires separate logic for storing literals vs other symbols. Instead, replace with a "store" operator `-> <name>` which takes the value on top of the stack and stores in the given name. 'let x 5` is equivalent to `5 -> x`.
* Add ability to have comments with `//`.
* Add `input` keyword for reading literals from stdin. (Currently parses either ints and bools, will eventually just return a string when supported and users will need to cast to others).
* Enhanced the interpreter to allow for either running a program or printing the bytecode.

More Operations

---

src/lexer.cpp
src/lexer.hpp

* Add `break` and `continue` keywords to use in while loops. These are implemented with `op_block_jump` under the hood.
* The tricky part here was having `break` and `continue` wrapped in `if` statements, as they would get collected up when parsing an `if` block. To fix this, `parse_if_statement` returns the op codes that it doesn't process and they get added back to the control flow stack. This can be made more efficient in the future.

Break and Continue

---

examples/recursion.anzu
examples/test.anzu
src/lexer.cpp
src/object.cpp
src/object.hpp
src/op_codes.cpp
src/op_codes.hpp
src/parser.cpp
src/parser.hpp

* Improved the lexer to be able to parse string literals.
* Removed `is_literal` and `parse_literal`. Now, `true` and `false` are keywords which are specifically handled in the parser, and ints are found and converted via `is_int` and `to_int`. For string, the lexer inserts a `__string` token before a token representing a string literal, which the parser uses to recognise a literal.
* Expanded the "numerical" operators a bit more. Specifically strings can be concatenated with `+`. May revert some of this however since it converts bools to ints before any operations which may not be desired.
* Added `(int)`, `(bool)` and `(str)` keywords which attempt to cast the top element of the stack to the specified type. The only conversion that can fail is `string` to `int`, and only succeeds if the …

String Literals

---

examples/test.anzu
src/anzu.m.cpp
src/object.cpp
src/object.hpp
src/op_codes.cpp
src/op_codes.hpp
src/parser.cpp
src/stack_frame.hpp

* Wraps the object variant in a class, encapsulating all the logic and removing the need to have `std::visit` everywhere.
* Adds a `debug` mode, which executes the program and prints each op code hit.
* Use `intptr_t` rather than `ptrdiff_t`, which are the same types but more accurate in how we use them.

Object Class

---

.vscode/launch.json
examples/test.anzu
grammar.txt
src/ast.cpp
src/ast.hpp
src/functions.cpp
src/lexer.hpp
src/object.cpp
src/object.hpp
src/op_codes.cpp
src/op_codes.hpp

* Added a grammar file. This is currently rough and will be refined as we move further from the stack based syntax.
* Add `anzu::node_variable` and `anzu::no_bin_op` to use alongside the existing `anzu::node_literal` in new logic for parsing expressions involving arithmetic operators, boolean operations and comparison operations.
* Removed most of the use cases that use `anzu::node_op`, which was always a temporary way to store op data in the tree.
* `.` has been replaced by the builtin function `print` for printing the top of the stack. There is a version that also prints a new line spelled `println`.
* Forth-style stack manipulation has been removed.
* All op codes for operations above are now handled by expressions and their ordering generated by the AST.
* All casts, printing and …

AST for Expressions

---

examples/euler.anzu
examples/test.anzu
src/ast.cpp
src/ast.hpp
src/lexer.hpp

* Added `=` as an assignment operator.
* Under the hood the assignment is parsed into an `anzu::node_assignment` which translates to `anzu::op_store` op code.
* Remove `anzu::node_op` as it is no longer needed.
* Removed the `->` operator.

Assignment Operator

---

.vscode/launch.json
examples/recursion.anzu
examples/test.anzu
src/ast.cpp
src/ast.hpp
src/functions.cpp
src/functions.hpp
src/lexer.hpp
src/op_codes.cpp
src/op_codes.hpp

* Reworked functions, new syntax is `function <name>(<args>) do <body> end`, similar to python.
* Functions now only return a single value, using the familiar `return <value>` syntax in python.
* If no return value is specified, a function returns `false`. This is temporary until a `null` value is added.
* Added the `discard_expression` and `assign_expression` nodes. Discard expressions evaluate the given expression, and then pop the top of the stack. It is currently not enforced that expressions must add a value to the stack, this will require further work. Assign expressions pop the value off the stack and store it.
* The above was to allow functions returning a value. If the function call is in a discard expression, the returned value gets popped. Function calls are another type of …

Functions with Parameter Lists

---

src/compiler.cpp
src/compiler.hpp
src/parser.cpp

* Renamed `node_function_call` to `node_function_call_expression` and added `node_function_call_statement`. Similarly for the `builtin` variants.
* The statement node adds in a `OP_POP` after when parsing, and is intended to be used whenever a function is called on its own with the return value discarded.
* The expression node is the version which is used when evaluating arithmetic/logical statements which is the current behaviour.
* If an expression is parsed now but not as part of an assignment, function call, return statement, while condition or if condition, the parsing fails.
* There is code duplication here, but I'll remove that when I switch to a variant implementation of the parse tree. The goal here is to make expressions a distinct type so that I can enforce that expressions are …

Function Expressions vs Statements

---

.vscode/launch.json
grammar.txt
src/CMakeLists.txt
src/anzu.m.cpp
src/ast.hpp
src/compiler.cpp
src/compiler.hpp
src/parser.cpp
src/parser.hpp

* Switched to a variant-based AST rather than an inheritance based one. This will allow us to implement more algorithms that operate on the tree, such as optimisations where the visitor needs to know the type of each node.
* This also allows us to implement "expression" nodes and "statement" nodes in the code. Now, `if` statements, `while` statements, `function/builtin` calls, assignments and `return` statements take expressions as arguments rather than statements, meaning it is not possible to create an AST where a `while` loop is passed as function argument (for example).
* Cleaned up the grammar file but it still needs work.
* All nodes are stored in `ast.hpp`, which also holds the print function. Now the `parser` module only contains the parsing code to create an AST and the …

Variant-Based AST

---

README.md
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/lexer.cpp
src/parser.cpp

* Remove `node_expr` from the `node_stmt` variant. A standalone expression is not a valid statement and causes a parser error anyway, expressions can only appear as child nodes of statements.
* Change the definition of the AST nodes to require fewer declarations. Now, the variant nodes are forward declared, followed by the node types, then the node variants are defined as subclasses of `std::variant`. This just results in fewer lines of code. Note: using `std::visit` on `std::variant` subclasses may not actually be guaranteed by the standard to work, but it does on MSVC at least. This is going to be fixed in C++23.
* The AST doesn't need to care about the differences between function calls and builtin calls, so the builtin nodes have been removed. Now when the compiler encounters a …

Simplify Parser

---

examples/test.az
src/CMakeLists.txt
src/ast.cpp
src/compiler.hpp
src/lexer.cpp
src/lexer.hpp
src/parser.cpp
src/parser.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* Move all keyword and symbols used by the language into a separate file, reducing some code duplication.
* Previously the sets defining token types was in the lexer, and the tokens were duplicated in the parser to give them variable names.
* Refer to these keywords via the constants in the new file, rather then copying them all over the place.

Vocabulary File

---

.vscode/launch.json
.vscode/settings.json
examples/test.az
src/CMakeLists.txt
src/anzu.m.cpp
src/optimiser.cpp
src/optimiser.hpp

* Add a flag `-o` which enabled optimisations.
* This PR adds an optimisation for const expressions. After constructing the AST, it is scanned to see if any expressions are made up of just literals and binary ops. If any are found, it is evaluated and replaced with a single `op_push_const`. For example, the anzu program `x = 2 * (3 + 1) / 2 + 10`, produces the following op codes:
```
0 - OP_PUSH_CONST(2)
1 - OP_PUSH_CONST(3)
2 - OP_PUSH_CONST(1)
3 - OP_ADD
4 - OP_MUL
5 - OP_PUSH_CONST(2)
6 - OP_DIV
7 - OP_PUSH_CONST(10)
8 - OP_ADD
9 - OP_STORE(x)
```
With optimisations turn on, this becomes:
```
0 - OP_PUSH_CONST(14)
1 - OP_STORE(x)
```
This has the added benefit binary operations between incompatible types being caught at compile time rather than runtime.

Optimising Const Expressions

---

examples/test.az
src/CMakeLists.txt
src/anzu.m.cpp
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/functions.cpp
src/lexer.cpp
src/object.cpp
src/optimiser.cpp
src/parser.cpp
src/parser.hpp
src/typecheck.cpp
src/typecheck.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* Add `typecheck.hpp`, with functionality for evaluating the type of an expression.
* When parsing an expression, the type is also evaluated, which will cause a bad exit if there is a type error.
* Types of variables are stored in the `parser_context`. New symbols are created via assignment statements, for loops and as function arguments, and all of these add type info into the context.
* At function call sites, the types of the expressions passed in are checked with the function signature.
* Returns values are currently not checked and require more work.
* This is a bit of a mess and needs a cleanup.
* Fix a bug in the optimiser where sub expressions that were known at compile time would not get replaced. Now, whenever a bin op with two constant children are found, it is substituted in …

Type Check Expressions

---

examples/euler.az
examples/feature_test.az
examples/recursion.az
examples/test.az
grammar.txt
src/compiler.cpp
src/functions.cpp
src/lexer.cpp
src/parser.cpp
src/parser.hpp
src/program.cpp
src/token.cpp
src/token.hpp
src/typecheck.cpp
src/typecheck.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* Replaced `do` and `end` with braces.
* Braced blocks are now a form of statement, and if statements now work the same way they do in C, where the bodies of the branches can be any statement, including braced lists. This allows for you to omit the braces when you only want one statement in the body.
* Because of the above, `elif` has been removed as a keyword too as `else if` can be used like in C.
* While loops, for loops and function defs also use braces, however this is implemented the same way the if statement is in that they now just accept a single statement, one of which is the braced syntax.
* Simplified the compilation of a for loop node. Now the "container" is just parsed as an expression since we can type check it as a list in the parser. In particular this allows the …

Cleanup Parser

---

examples/euler.az
examples/test.az
src/anzu.m.cpp
src/ast.cpp
src/compiler.cpp
src/parser.cpp
src/parser.hpp
src/typecheck.cpp
src/typecheck.hpp

* The parser was a bit of a mess doing several things, now it only parses the tokens and does no check on the types of anything.
* The type checking has been moved to a separate stage, to run the pipeline up to and including checking, invoke the interpreter with the `check` command.
* Optimisations now only happen after typechecking. Currently the `-o` flag does nothing for `parse` and `check` stages, only for `com` and `run`. I will change this in the future.
* Removed `parser_context` since the parser now only needs the tokens. This works for functions because checking for a left paren after a name is unambiguously a function call, so it doesn't need to look the name up to check that.
* The rest of the `parser_context` is now called `typecheck_context` and is only needed in the type …

Move Typechecking out of Parser

---

README.md
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/optimiser.cpp
src/parser.cpp
src/typecheck.cpp

* All ast nodes now store a `token` passed through from the lexer by the parser. This allows for line/col values to be in the typechecker error messages.

Tokens in AST

---

examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/optimiser.cpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/typecheck.cpp

* Previously, you could only write out list literals where the contents were also literals, so the following would be invalid:
```
x = 5
y = [1, 2, x]
```
* This PR adds a new expression node, `node_list_expr`, which contains a list of child expression nodes for its children.
* A `node_list_expr` compiles down to evaluating the nodes, pushing them to the stack, then calling the new op code `op_build_list(n)`, which takes the top n elements off the stack and pushes a list containing them.
* With optimisations on, a list literal is optimised down to a single op code, so this is not a regression in that case.

List Expressions

---

src/ast.cpp
src/functions.hpp
src/lexer.cpp
src/object.cpp
src/optimiser.cpp
src/program.cpp
src/runtime.cpp
src/token.hpp
src/type.cpp
src/typecheck.cpp
src/utility/overloaded.hpp
src/utility/peekstream.hpp

* Fix compiler warnings.
* Move all the `overloaded` copies to `utility/overloaded.hpp`.
* Use `format_comma_separated` in the repr implementation for lists.

Housecleaning

---

README.md
examples/feature_test.az
examples/test.az
src/type.hpp
src/typecheck.cpp

* Currently, the type checker was disallowing calls to functions from within other functions, only nested functions written inside the given functions, since it only checked the local scope to lookup function signatures. This relaxes the checker to look at previous scopes for function definitions is the current scope is missing it.
* The scopes are now stored in a vector instead of a stack to make all elements accessible.
* The checked signatures that are stored in a map for each function def in now stored in an unordered set rather than a vector. To implement this, signatures are now hashable. The hash ignores the arg names, which we may want in the future?
* Without the type checker, compiled anzu code can call functions from other functions fine, but this is due to the …

Lookup Functions Within Other Functions

---

.vscode/launch.json
examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/object.hpp
src/optimiser.cpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/runtime.hpp
src/typecheck.cpp
src/utility/scope_timer.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* In the current implementation, the runtime maintains scopes and performs hash map lookups whenever a variable is referenced.
* This is expensive and slow. A better approach is to store all variables in a vector, calculate their location at compile time, and then at runtime we can just index into the stack.
* The `runtime_context` now just stores a vector of objects. Each variable in a function is now stored as an offset from a "base_ptr", which is set when that function is invoked.
* Now that stored variables and the "stack" are all in the same data structure, various optimisations can be made to reduce the number of pops and pushes.
* An example of the above are function calls and returns no longer doing copies. Since args get pushed to the stack before invoking a function, the …

Resolve Variable Names at Compile Time

---

.vscode/launch.json
examples/feature_test.az
examples/test.az
src/compiler.cpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/typecheck.cpp

* Disallow nested functions. They serve no purpose since we don't have closures.
* In the compiler/typecheck contexts, replace the stack of "scopes" with a map of functions, a map of global variables, and an optional map of local variables for when inside a function.
* Global variables can be read/modified in a function via assignment. You can also shadow global variables using a declaration. All uses of the variable name after a declaration will refer to the local variable.
* The load/save variable op codes have been replaced with local and global versions. This is mainly for debuggability.

Fix Global Variable Lookup

---

examples/test.az
src/runtime.cpp

* Turns out, return values were broken. Instead of returning the return value, they returned the first function parameter (or null).
* This is because functions leave behind a single value, but the base pointer starts at the first function argument.
* `pop_frame` in the runtime now overwrites the first function arg with the return value.

Fix Function Return Values

---

.vscode/settings.json
examples/test.az
src/ast.cpp
src/compiler.cpp
src/functions.cpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/runtime.hpp
src/token.cpp
src/token.hpp
src/type.cpp
src/type.hpp
src/typecheck.cpp

* This is a very hacky implementation, is probably very error prone, and is lacking a lot of features.
* The bulk of this PR is allowing for objects that are larger than one block in size. There are probably some things I've missed since the assumption that an object == a single block is everywhere in the code.
* Builtin functions that accept generic objects are currently broken.
* `print` and `println` are exceptions to the above. I've hacked those in as special cases to work properly. When compiling either of these functions, we resolve the function signature based on the parameters passed in so the size is known, so the correct number of blocks get passed in when called. This needs to be generalized by resolving all generic signatures at compile-time, which is doable, just tedious.
* …

Add `vec2` Type

---

.vscode/launch.json
examples/test.az
src/compiler.cpp
src/functions.hpp
src/object.hpp
src/parser.cpp
src/type.cpp
src/type.hpp
src/typecheck.cpp
src/typecheck.hpp

* The goal with these PRs is to un-hardcode the `vec2` impl, replace the hacks with features, and eventually remove `vec2` from the code altogether, replacing it with a definition written in pure anzu.
* In `compiler::compile_function_call`, remove the hardcoding of `vec2` to return the size of any given type called as a function. This is not usable yet for fundamental types as the typechecker needs to be made smarter, but this won't need changing when we do.
* Rename `type` to `type_name`, as the fields will eventually be moved out, because we need `type_name` to be constructible from the source code.
* Merge `type_class` into `type_simple`.

Clean up `vec2` Part 1

---

examples/feature_test.az
src/CMakeLists.txt
src/compiler.cpp
src/functions.hpp
src/operators.cpp
src/operators.hpp
src/program.hpp
src/typecheck.cpp

* We had very similar logic in the typechecker and the compiler for handling binary operators. The type checker takes two type and an op and works out the result type, while the compiler works out which function is needed to carry out the operation.
* This had to be kept in sync, making adding more operations error prone. This PR moves it all into the same function.
* The replacement code is also much cleaner.

Clean up Bin Op Resolution

---

examples/test.az
src/compiler.cpp
src/parser.cpp
src/program.hpp
src/runtime.cpp
src/type.cpp
src/type.hpp
src/typecheck.cpp

* Unhardcode the remaining vec2s in the parser, typechecker and compiler.
* Remove the function that calculates the block size of a type. This has been replaced with a function on the `type_store`.
* The `type_name` no longer contains the fields of the type, making it possible to parse a full `type_name` from source code.
* The set in the type store is now a map, mapping class names to field lists.
* Remove `signature` objects from the runtime, instead only storing the arg sizes. This is because we could no longer calculate the size of types from the signature since we need the type store. Doing this at runtime was bad anyway so this is also an optimisation.

Clean up `vec2` Part 2

---

examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/functions.cpp
src/operators.cpp
src/parser.cpp
src/program.hpp
src/typecheck.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Make it possible to read and write to fields of objects (only vec2 exists currently).
* `node_field_expr` is the expression node for fetching the field.
* `node_field_assignment_stmt` is the statement node to writing to the field.
* The above can possibly be combined when we have references.
* Remove `builtin_first` and `builtin_second`, since we can now write `v.x` and `v.y`.
* For attribte access, `.` is obviously now a special symbol.
* `struct` is now a keyword, and added `node_struct_stmt` to the ast. It currently is unused.

Attribute Access

---

.vscode/launch.json
README.md
examples/feature_test.az
examples/test.az
src/anzu.m.cpp
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/compiler.hpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/type.cpp
src/type.hpp
src/typecheck.cpp
src/typecheck.hpp

* It is now possible to define structs in anzu code with the `struct` keyword.
* `vec2` has been removed from the interpreter since it can now be added in 4 lines of a script.
* The `type_store` from the typechecker is now also passed along to the compiler with the `expr_types` so that the types do not need to be parsed again. This means that there is no logic in the compiler for struct definitions, so custom types are just as efficient as builtin ones would are.

User Defined Structs

---

examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/typecheck.cpp

* `node_assignment_stmt` now has a `node_expr_ptr` position to store to, rather than a string name. It fails the typechecker if the position expression is a different type to the value on the right, and it fails to compile if it isn't an lvalue, which is currently only vaguely defined.
* Valid expressions on the left are `node_variable_expr`, `node_field_expr` and `node_deref_expr`, the last of which is handled differently (see further down).
* `node_field_assignment_stmt` and all related code has been deleted since the standard assignment statement can handle that case now.
* Remove the `name` attribute from the `op_save_global/local` op codes.
* Add `op_save_to_addr` which pops a pointer from the top of the stack and stores the next object at that location. Used to implement assigning …

Generalised Assignment

---

examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/typecheck.cpp

* Current parsing was brittle, as `(deref x).y` would not parse correctly, and we could also not have statements such as `get_pointer() = 5` since that would try parsing first as a function call.
* The solution here is to remove the special case for parsing function calls, and allow for parsing an expression first, then possibly checking for an assignment.
* This change allows for any expression to be written down, even if pointless. For example, writing just `3 + 4` was invalid previously, whereas now it will correctly generate code that will evaluate the result and then immediately pop it.
* Removes the `node_function_call_stmt` statement and replaces it with `node_expression_stmt`, which has much simpler logic since it just delegates to an expression node, removing duplicate code that …

Expression Statements

---

src/compiler.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/runtime.hpp

* In all the places in the runtime where an `intptr_t` was used, use `size_t` instead since we don't need signed values.
* Small simplification in some places.
* For jump op codes, the unset value is now 0 instead of -1, which is also fine because a jump of 0 would be an infinite loop, so its definitely an unused value.
* When compiling a `node_literal_expr`, remove the assert than an object just only have one value, I don't think there's any harm in an op code having more than one block, even if it can't currently happen.
* Remove the `name` field from some of the op codes that didn't need it.
* `op_load_literal` now stores a `std::vector<block>` rather than an `object`, removing all type info from the runtime.

`size_t` instead of `intptr_t`

---

examples/test.az
src/operators.cpp
src/parser.cpp
src/type.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Replace `addrof` keyword with `&`.
* Replace `deref` keyword with `*`.
* Introduce `!` which parses as a `node_unary_op_expr` for logical not. Only usable for bools.
* Fix precedence for address of and dereference operators. Previously the argument for the operator was parsed as an entire expression, really it should be a single factor (you can apply it to an entire expression using parens). This fix was spotted when implementing arithmetic negation.
* Make `ptr` a keyword.

C-style Symbols for Pointers and Logical Not

---

examples/test.az
src/compiler.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/runtime.hpp

* The main problem solved by this PR is that statements such as `(*v).x = 5` were invalid as we couldn't access fields on deref expressions. This is because all the load op codes needed the positions known at compile time, which requires knowing the values of pointers at compile time, and we don't store value info.
* Completely changed how we save and load to memory to lean more heavily on pointers.
* Now, if we want to save, we must first load the position in memory onto the stack and use one of the op codes for storing to an address. Similarly for loading, we now always push a memory location and then deref it.
* Renamed and added/removed a lot of op codes:
* `op_load_addr_of_global` renamed to `op_push_global_addr`.
* `op_load_addr_of_local` renamed to `op_push_local_addr`.
* …

Generalised Assignemt: Part 2

---

examples/feature_test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp

* For loops have been temporarily removed.
* This is because lists are completely broken for types of size 1, with size 1 types only working via a hack.
* When lists are working properly, for loops can be added back, for now they just serve as more stuff that need updating.

Remove For Loops

---

.vscode/launch.json
examples/feature_test.az
examples/recursion.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/functions.cpp
src/object.cpp
src/object.hpp
src/operators.cpp
src/operators.hpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/type.cpp
src/type.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* `block_list` is now gone, with lists being stored directly in memory on the stack.
* Added `type_list` to the type variant. The next step will be to remove all generic stuff since it is completely broken, and bake lists and pointers into the language type system properly.
* Lists now act like arrays in that they cannot be resized.
* Added in `type_of_expr` to the compiler, which works out the type of an expression without evaluating it. This duplicates a bit of code which can hopefully be cleaned up later.
* Remove all the list builtin functions.
* Remove `op_build_list`.
* Replace `op_modify_addr` with `op_modify_ptr`. These do the same thing, except that `op_modify_ptr` fetches the offset and size from the stack, rather than it being baked into the op code. This allows for modifying a …

Stack-based Lists

---

examples/feature_test.az
examples/test.az
src/compiler.cpp
src/functions.cpp
src/parser.cpp
src/type.cpp
src/type.hpp
src/vocabulary.cpp

* Generic types are completely broken and unworkable, so this strips it out so we can revisit it later.
* Added `type_ptr` to the type variant.
* Removed `type_compound` and `type_generic`.

Remove Generic Types

---

README.md
src/compiler.cpp
src/type.cpp
src/type.hpp
src/utility/value_ptr.hpp

* Added `value_ptr`, a smart pointer with value semantics.
* `value_ptr` is used in the type variant for recursive types, rather than using a vector which was a hack.

`value_ptr` for Type Variant

---

README.md
examples/test.az
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/type.hpp

* Function definitions are now stored with the arg types in the hash as well, allowing for function overloading.
* Added compiler checks to make sure that structs and functions cannot share names.
* Compiling function calls is a bit messy and could do with a cleanup.

Function Overloading

---

src/compiler.cpp
src/functions.cpp
src/object.cpp
src/object.hpp
src/operators.cpp
src/runtime.cpp

Both null and boolean values are now implemented with `block_byte` under the hood.

Remove `block_null` and `block_bool`

---

src/object.cpp
src/object.hpp
src/operators.cpp
src/runtime.cpp
src/type.cpp

* Remove `block_ptr`. Instead we simplify push 2 `block_uint`s.
* Size of pointer types is now 2.
* Simplify `ptr_addition`. The type map is not needed since we didn't need to pass the size in because the ptr already had the size.
* This was mainly just a runtime change as `block_ptr` is not used in the compiler.

Remove `block_ptr`

---

examples/feature_test.az
examples/test.az
src/compiler.cpp
src/functions.cpp
src/lexer.cpp
src/object.cpp
src/object.hpp
src/operators.cpp
src/operators.hpp
src/parser.cpp
src/token.cpp
src/token.hpp
src/type.cpp
src/type.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* Replaced `float` type with `f64` types, represented in bytes.
* Block variant now only stores uint64s and bytes now.

Remove `block_float`

---

.vscode/launch.json
examples/feature_test.az
examples/test.az
src/compiler.cpp
src/functions.cpp
src/lexer.cpp
src/object.cpp
src/object.hpp
src/operators.cpp
src/parser.cpp
src/runtime.cpp
src/token.cpp
src/token.hpp
src/type.cpp
src/type.hpp
src/vocabulary.cpp
src/vocabulary.hpp

* Everything is now stored as bytes.
* The bytes are still wrapped in a variant, which we can remove next.
* Replaced `uint` as a type with `u64`.

Remove `block_uint`

---

src/compiler.cpp
src/functions.cpp
src/functions.hpp
src/object.cpp
src/object.hpp
src/operators.cpp
src/operators.hpp
src/parser.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/runtime.hpp
src/utility/memory.hpp

* No more block variant, data is represented in the runtime as `std::byte`.
* Refactored builtin functions and bin op resolutions.
* Builtin functions are now the same a mem op functions to reduce the number of redundant allocations.
* Replace `op_load_literal` with `op_load_bytes`.
* The runtime now just stores two `uint64_t`s and a `std::vector<std::byte>`.

Remove `block` Variant

---

.vscode/launch.json
examples/test.az
src/compiler.cpp
src/operators.cpp
src/operators.hpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/type.cpp

* Until now, anzu has had "fat" pointers, which store a size as well as a location. This is actually an overcomplication since all types are known at compile time and so sizes are known.
* The sizes are now stored in the `op_save`, `op_load` and `op_pop` op codes, and pointers are just locations now.
* This simplifies a few things, for example, `op_modify_ptr` just modifies the location of the pointer, the size of the type does not have to be considered at all. This works because when we eventually make use of it to load or save, the size is already in the op code.
* Sadly, the pointer addition operation requires us to pass the type store again since we cannot fetch the size from the stack.

Slim Pointers

---

.vscode/launch.json
examples/test.az
examples/vector.az
src/compiler.cpp
src/lexer.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp

* Almost fully implemented destructors.
* Worked out at compile time which objects get destructed at the end of scopes as well as at `break`, `continue` and `return` statements.
* Added scopes around `while` loops when when a `break` or `continue` occurs, we can destruct objects within the scope. Will also make it trivial to allow things like `while (x := 0, x != 10) {}` where the `x` is within the `while` scope but not in the braces scope. Currently the while scope is always empty and only within the scope stack so that we know how far up the stack we need to destruct objects.
* If an class `T` has a function called `drop`, it is called when the object goes out of scope. The signature must be `(&T) -> null`, however this is not currently checked.
* There will be problems with this when …

Destructors

---

examples/test.az
src/compiler.cpp

* When arrays go out of scope, call the destructor of the inner type for each element, right to left.
* Destructors now recurse through member variables and call those destructors too, starting from the last.
* Bugfix: Getting the return type of a constructor is now handled specially, it previously looked for a function definition which didn't exist. Was causing expressions like `[object(5); 6]` to be invalid since the compiler couldn't work out the size of the list.

Full Destructor Implementation

---

examples/list_destruction.az
src/compiler.cpp

* I missed an op code that correctly set the pointer to the array element being destructed.
* I missed this because in my example, the list was the only variable in the program, so `push_var_addr(com, tok, var)` just pushed a zero, so `push_literal(com, index * inner_size)` was actually pushing the correct position on its own. With another variable declared before it, it all goes wrong.

Bugfix: List Destructors

---

examples/test.az
src/object.cpp
src/parser.cpp

* If a function returns `null`, the `-> null` may be omitted from the function definition.
* Removed an unused function.

Make Null Return Optional

---

anzu-lang/syntaxes/anzu.tmLanguage.json
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/object.hpp
src/parser.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Two new special member functions `fn copy(self: &T) -> T` and `fn assign(self: &T, other: &T)`
* `copy` is called for declarations (`x := y`) and function parameters if the right hand side is an lvalue. If it's an rvalue, no copy constructor is called and the object is just moved (memcpy'd).
* `assign` is called for assignments (`x = y`) if the right hand side is an lvalue. If it's an rvalue, it is similarly just moved.
* `copy` and `assign` can be defaulted with the syntax `fn copy = default` and `fn assign = default`. This just makes them act like a memcpy which is how fundamental types behave.
* By default, `copy` and `assign` are deleted.
* Really, the `= default` should be the default behaviour, otherwise it's a bad name. It's also less verbose for simple types.
* The compiler …

Copy and Assignment

---

examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* Fixes a bunch of holes, most notably copying and assigning from arrays. These now call the correct functions if provided.
* Fixes a bug where pointers were classed as not copyable/assignable. Introduced `is_type_trivially_copyable` which is true if the type is fundamental, a pointer, or an array of trivially copyable types. Currently only defined for builtin types (although pointers to user types are fine).
* Disabled `= default` for copy and assign for now, since that needs to call the copy/assign functions for the members rather than just doing a memcpy. With that, there should be no holes in the lifetime model now.
* Will reenable `= default` at some point, and make that the actual default when it is done. For now, user types are not copyable/assignable by default and implementations …

Copy/Assign for Arrays

---

src/compiler.cpp
src/lexer.cpp
src/parser.cpp
src/token.cpp
src/token.hpp

* We had duplicate error checking functions in the parser and compiler, this PR moves them all onto the token class to make them available everywhere, and also makes the calls simpler.

Move Asserts to Token

---

examples/feature_test.az
examples/test.az
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* Remove `=delete` and `=default` for now.
* `copy` and `assign` are deleted by default, and get the implementation if explicitly defined.
* Added `push_object_copy` to the compiler. This evaluates an expression and puts it on the stack, calling the copy constructor if it's an lvalue. This really should replace `push_expr_val` but I can't quite figure out how to do that yet. Potentially will be a huge simplification if I can do it.
* The above will also fix a bunch of other potential holes in the type system
* Added `pop_object`, which assumes the top of the stack contains an object of a certain type, then calls the destructor and pops the bytes. Used in order to call destructors for unassigned expressions. Should be the default function for removing data from the stack.
* Renamed a lot …

Copy/Assign Cleanup

---

examples/test.az
src/compiler.cpp

* This commit was accidentally left off the last PR.
* Moves the handling of lists from `call_destructor_named_var` to `call_destructor`, allowing for destructors to get called on arrays that are not assigned to variables.

Fix Destructors for Temporary Arrays

---

src/compiler.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp

* Rename `op_jump` to `op_jump_rel`.
* Rename `op_jump_if_false` to `op_jump_rel_if_false`,
* Rename `op_function` to `op_jump_abs` and remove the name field because it isn't used at runtime. This will make it easier to change to a real byte code in the future.

Rename Jump Op Codes

---

anzu-lang/syntaxes/anzu.tmLanguage.json
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Add `lengthof` operator that is similar to `sizeof`, but returns the number of elements in an array. It is a compiler error to call `lengthof` of a non-array object.
* Will be used to implement for loops.

`lengthof` Operator

---

anzu-lang/syntaxes/anzu.tmLanguage.json
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Was added to help implement for loops, but ended up not being needed.

Remove `lengthof`

---

README.md
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Add `loop {}` syntax, just like in Rust.
* `while` and `for` loops are rewritten to be in terms of basic loops.
* `break`, `continue` and `loop` now use absolute jumps instead of relative loops, easier to think about.

Basic Loop

---

.vscode/launch.json
examples/euler.az
examples/test.az
src/compiler.cpp
src/program.cpp
src/program.hpp
src/resolver.cpp
src/runtime.cpp

* I changed to relative jumps ages back for some reason, but it just makes the code harder to reason about.
* Now that I've added back absolute jumps, this replaces all remaining relatives ones.
* Removed the relative jump op codes.
* Fixed an off by one error with the break statement in the last PR.
* Fixed pointer arithmetic, dealt with specially rather than in the resolver since it requires extra work to multiply by the size of the type.

Replace Relative Jumps with Absolute Jumps

---

.vscode/launch.json
anzu-lang/syntaxes/anzu.tmLanguage.json
examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp
src/vocabulary.cpp
src/vocabulary.hpp

* Added `typeof`, which works similarly to `decltype` in C++, can be used in the code wherever a type is expected.
* Implemented by replacing `type_name` in the ast with a variant containing either a `type_name` or a `node_expr_ptr` (both wrapped in structs for now). We resolve these back to `type_name`s in the compiler.
* Resolving of return types for functions occurs after the parameters have been declared, meaning the return type can depend on the args, for example `fn add(x: i64, y: i64) -> typeof(x + y)`.
* Implement `type_of_expr` in terms of `push_expr_val`. It now compiles the expression to get the type, then pops off the op codes to leave the program unchanged.
* This actually found a bug in the `feature_test`, where an `i64` was being used as an array subscript since the old …

`typeof` Operator

---

src/compiler.cpp
src/object.hpp

* We previously had a map and a set, with the former being keyed on name and params, and the latter being used to verify that a struct doesn't get named the same as a function.
* This was even worse because the function name, contained the struct name, which wasn't great design.
* Now it's all replaced by a multi-layer map where the keys go `struct_name -> function_name -> params -> info`. Global functions are now stored as member functions of a `<global>` struct, but this is an implementation detail only used for accessing the function map.
* It also turns out the compiler didn't prevent `break` and `continue` being used outside of loops, and would crash if that was the case, this has been fixed.

Improve Function Storage

---

examples/euler.az
examples/test.az
examples/vector.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp

* Remove `node_member_function_call_expr`; now that we have `typeof` in the language, member function calls `x.f(...)` can now be parsed as `typeof(x)::f(&x, ...)` (although this syntax is not currently allowed in the language yet, this is purely a parsing change).
* Because the above change refers to `x` twice, the expr node that represents it must be held in two places in the ast, so switched from `unique_ptr` to `shared_ptr`. There may be a better way to do this.

Unified Function Calls

---

examples/feature_test.az
examples/stdlib.az
examples/test.az
src/compiler.cpp
src/functions.cpp
src/object.hpp
src/program.cpp
src/program.hpp
src/runtime.cpp
src/runtime.hpp
src/utility/memory.hpp

* The compiler now also outputs an extra `std::vector<std::byte>` containing all string literals in the program.
* String literals in a program are now of type `char[]` and span over read only memory.
* Now able to remove the hacked in `print` and `println` builtin functions for printing strings, these are replaced by functions in the new `stdlib.az` which accept `char[]`. Implemented using the builtin functions for `char`.
* Currently, trying to write into read only memory results in a runtime error, but when we have `const` we can make this a compile time error.
* In the future, if we turn this into a true bytecode, the read only memory can exist within the program bytecode, for now this is a simpler solution.
* If a newly declared string literal is a substring of an existing literal, …

Read-Only Memory

---

examples/feature_test.az
examples/test.az
src/compiler.cpp
src/object.cpp

* Currently only one function is allowed per name by mistake since it clears the signature map in the compiler for that name when a new one is given. This removes that line allowing for the map to have multiple functions again.
* This fixes the error in `feature_test` where it couldn't find `println(char[])` despite the standard library being imported. This was because further down it implemented `println(vec2)` which deleted the `char[]` function pointer from the compiler.
* Refactors `call_destructor` to use visitation instead of the janky `is_*_type` which I want to move away from.
* Refactors `type_store::size_of` to use visitation at the top level, with the rest of the implementation moving into the case for `type_simple`.

Fix Function Overloading

---

src/compiler.cpp
src/functions.cpp
src/functions.hpp
src/program.cpp
src/program.hpp
src/runtime.cpp

* `op_builtin_call` now stores an id to lookup the builtin function at runtime, meaning it is now trivial to turn into bytecode.
* The builtin map has been replaced by a builtin array.
* Printing builtin op codes now shows the signature of the function as well as just the name.
* Removed the ability to print pointers since it was hacked into the builtins system. We should implement this properly with untyped points and casting if we really want it.

Fixed Size Builtin Op Code

---

examples/test.az
src/compiler.cpp
src/program.cpp
src/program.hpp
src/runtime.cpp

* `op_assert` messages are now stored in read only memory, reducing a lot of potentially duplicated messages in the op codes. Also makes the op code a known size.
* It is now possible to convert to a true bytecode; all op codes only are trivial structs.

Move Assert Messages into ROM

---

src/program.cpp
src/program.hpp

* Puts each op code def onto one line, making it easier to see the available op codes.

Make `program.hpp` Simpler

---

examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/lexer.cpp

* Added `push_literal_call_frame` which pushes two `u64`s onto the stack, replacing the two `push_literal_u64` for each function call. Makes it easier to see where function calls start.
* Renamed `push_global_addr` to `push_literal_ptr`.
* Renamed `push_local_addr` to `push_literal_ptr_rel`.
* Fixed a bug when calling function pointers. When we have a named variable containing a function pointer, it would first try and check to see if its the name of a builtin, but in doing so would push object copies to the stack, and would leave them there before moving onto loading everything for the ptr call. Now, we only evaluate the types to get the signature for the builtin check, with no extra stuff pushed to the stack. This was spotted when switching to the call frame op code, because we started …

Call Frame Op Code

---

.vscode/launch.json
examples/std/string.az
examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp

* Rename all `push_literal_*` op codes to `push_*`.
* Added `push_string_literal`, which is equivalent to pushing a pointer + size. Alternate name could have been `push_char_span`, but named it string literal because it is assumed that the pointer always points to read-only memory.
* Add a constructor to `string` that accepts a `char[]`.

String Literal Op Code

---

examples/std/string.az
examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp

* The bug with function pointers was in `op::call`; storing the next position of the program pointer still had a +1 left over, causing the bad read. This was fixed in `op::function_call` but not here.
* Removed `op::function_call`, just use `op::call` everywhere now since it's equivalent to a `op::push_u64` followed by `op::call`.
* Implemented the `transform` function on the `string` class, which was the original way I noticed this bug.
* Remove some unused functions from the bytecode module.
* Renamed `read` to `read_advance`.
* The `reinterpret_cast` uses in the bytecode to convert from bytes to a `string_view` is not undefined behaviour, so those comments have been removed and the code has been cleaned up a bit.

Function Pointer Calling Fix

---

examples/euler.az
src/bytecode.cpp
src/compiler.cpp
src/lexer.cpp
src/token.hpp
src/utility/print.hpp

* I upgraded my compiler which landed the C++20 defect report to make an incorrect number of format args to `std::format` a compile time error, which resulted in compiler errors.
* Wrapper functions for `std::format` now take a `std::format_string<Args...>` instead of `std::string_view`.

Fix Format Defects

---

README.md
examples/test.az
src/ast.cpp
src/ast.hpp
src/bytecode.cpp
src/compiler.cpp
src/functions.cpp
src/lexer.cpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/token.cpp
src/token.hpp

* Added first implementation of references. Most likely riddled with bugs and will likely reimplement.
* Create a reference using postfix `~`, this is a temporary spelling, eventually references will be "visible" in the code, they will just be used to implement better function calls.
* Acts like references in C++, they cannot be reassigned, cannot be null, and act like the type they're referencing. Implementation mostly involves just going through the compiler and treating references specially.
* Values and bind to references in function arguments and vice versa.
* Added concept of convertibility between types.
* You cannot have functions overloaded on reference, eg; `fn foo(x: i64){}` and `fn foo(x: i64~) {}` is a compiler error as it is ambiguous.

References

---

.vscode/launch.json
examples/test.az
src/compiler.cpp
src/object.cpp

* Using the new concept of convertible types that allow for objects to bind to reference function parameters, we can also allow for other types to bind to different types too.
* It is now possible to pass arrays to functions that accept a span. Eg; given `fn foo(arr: i64[]) {}` and `arr := [1, 2, 3]`, you would previously have to write `foo(arr[])`, now you can simply wrote `foo(arr)` (both ways are still allowed).
* Fix a bug with calculating the size of function arguments. Previously used the given arguments rather than the actual parameters, which was fine before adding references, but now they can disagree.

Arrays Convert to Spans

---

examples/feature_test.az
examples/list_destruction.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* They've been referred to as both for ages now. I started with them called arrays back when everything was dynamically typed. When I switched to static typing I started referring to them as arrays because they had to be fixed size.
* Now all functions related to arrays are spelled correctly, no more having code using a mix of `is_list_type()` and `array_length()`.
* Simplified the `push_function_call` function now that the second and third args are just sub elements of the same object in all cases.

Rename Lists to Arrays

---

examples/test.az
src/bytecode.cpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* Replace `type_simple` with `type_fundamental` and `type_struct`
* Simplify a bunch of other functions to use `std::visit` instead of needing to use functions like `is_type_fundamental`, which has been deleted.
* Bugfix: Empty structs had a size of zero which caused some problems. These now have a size of 1.
* Bugfix: Correctly pop the return values from `assign` and `drop` calls. This was leaving excess data on the stack at the end of the program, which was almost certainly causing other bugs as objects would be misaligned.
* Improvement: `type_store::contains` is now stronger in that it will check the inner types for arrays, spans, pointers and references. In practice this doesn't change anything but it makes the function less surprising.
* Improvement: Trying to call …

Type Category for Fundamentals + Bugfixes

---

README.md
examples/test.az
src/compiler.cpp

* Currently, the loop parameter of a for loop is a pointer, otherwise we would have only gotten copies.
* Now that we have references, for loops can use them instead. Done by simply changing the type of the declared variable.

References in For Loops

---

examples/feature_test.az
examples/list_destruction.az
examples/recursion.az
examples/std/string.az
examples/std/vector.az
examples/test.az
src/compiler.cpp
src/parser.cpp

* The `self` and `other` arguments of member functions are now expected to be references, not pointers, eliminating most uses of `@.` in the examples.
* Bugfix: in `push_val_underlying`, the load was wrong; it would only load 8 bytes (size of a reference), instead of the actual size. 
* Modified `is_assignable` to support assigning from a reference to a concrete value. Previously only support from concrete to reference. The implementation of loading function args uses `push_object_copy` here so copy constructors will be correctly invoked.

Make `self` a Reference

---

README.md
examples/std/vector.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/lexer.cpp
src/parser.cpp
src/token.cpp
src/token.hpp

* Added `unsafe { ... }` syntax. Certain language features will only be usable in unsafe blocks.
* `new` and `delete` are only usable in unsafe code.
* Motivation for this is to add a version of `reinterpret_cast` and placement-new, which will allow a better vector implementation written purely in anzu. Vector will need to store a span of bytes rather than actual objects in order to avoid needing to call constructors for the "empty" elements. Currently the vector of ints zeroes all elements, which isn't generic enough (of course, a generic vector requires templates, but that's another problem to solve).
* The scope logic is all a bit messy, it would be good to refactor it all into a single data structure.

Unsafe Block

---

examples/std/string.az
examples/test.az
src/bytecode.cpp
src/compiler.cpp
src/object.cpp
src/parser.cpp

* Updated the standard string to use `unsafe` around `new` and `delete`, completely broken before.
* Made the check for a return statement more flexible. Previously, a non-null returning function required the last statement in the function be a `return` statement. Now, the last statement can also be an `unsafe` block, provided the last statement in the block is a `return`. This can generalise to `if` statements too.
* Unary and binary operations were completely broken, with only `+` working. Should always add braces! Now it all works correctly. Only spotted it because I tried printing `x := -5` and was seeing 5.
* Function pointer types are now spelled with a `fn` at the front, eg `fn(i64) -> bool`. This makes it unambiguous to parse, and also...
* Parens are now allowed within types, …

Improve Unsafe Blocks and Type Parsing

---

examples/test.az
src/object.cpp
src/token.cpp

* When printing types, if a subtype has a space in it, add parens around it, so you can distinguish (for example) `fn(i64) -> bool[3u]` from `(fn(i64) -> bool)[3u]`.
* Changed the string representation of `kw_function` from "function" to "fn" to match the language.

Improve Type Printing

---

examples/test.az
src/compiler.cpp
src/object.cpp

* Given how member functions are implemented (as just regular function calls), the only reason this wasn't working was due to a bug; the struct name is used as the namespace when searching for the funciton, but `const` wasn't being stripped off, so the function couldn't be found..
* Also added `__dump_type` compiler intrinsic function for dumping out types of variables.

Const Member Functions

---

examples/test.az
src/compiler.cpp
src/functions.cpp
src/functions.hpp
src/object.cpp
src/object.hpp

* `are_types_convertible_to` and `push_function_arg` both had very similar logic, one was for checking if a conversion is possible, the other is for compiling that conversion. These were both written in different ways and made it a complete mess to maintain.
* The original implementation of both of those functions probably had bugs in it where they disagreed.
* Created a new function, `get_converter(type_name src, type_name dst)` which returns an optional function; if the conversion is possible, the returned function is the logic to compile it. Both of the above functions are rewritten in this new one.
* Cleaned up all the call sites of `push_function_arg`, the only reason the error checking code was at the call site was because of a failed attempt to clean this code up earlier.

Conversion Code Refactor

---

examples/test.az
src/compiler.cpp
src/utility/common.hpp

* Bug: Array destructors were incomplete; it would only call the `drop` function for the inner type and not also recurse through the fields to call those destructors after. This is fixed by just looping backwards through the array and calling `call_destructor` recursively to delegate to the implementation for struct types.
* Bug: Looping through the fields of an inner type was broken because we were trying to lookup the field name on the inner type rather than the outer type. In other words, `push_adjust_ptr_to_field(com, tok, field.type, field.name)`, should just be `push_adjust_ptr_to_field(com, tok, type, field.name)`, passing the type that has the field rather than the type of the field itself.
* Added a `range` function to wrap `std::views::iota` to be more like python.
* Used `zip` …

Fix Destructor Bugs

---

README.md
examples/feature_test.az
examples/list_destruction.az
examples/std/file.az
examples/std/string.az
examples/std/vector.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/lexer.cpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/token.cpp
src/token.hpp

* Added `ref` as a keyword.
* Declare aliases to existing objects with `ref`: `ref x := y`. Similar to `let` and `var`.
* It's not possible to create a const ref alias to a mutable object, but I don't think it's a big deal. If you want to make a const ref to a mutable object, create a function and pass it there.
* Specifying a function param as a ref is done to the left of the param name, rather than part of the type, similar to the above syntax for creating local references. eg in `fn foo(ref x: const i64)`, `x` is of type `const i64` but is also a reference so no copy happens. `(ref x: i64)` is a mutable reference to an i64.
* `copy` and `assign` now use const references where appropriate: `copy(ref self: const T) -> T` and `assign(ref self: T, ref other: const T)`.
* Optimise …

Keyword `ref`

---

examples/feature_test.az
examples/test.az
src/compiler.cpp

* When given a pointer `p`, `p.x` is equivalent to `p@.f`. This is recursive and can dereference multiple times eg for a `i64&&`, `p.x` is equivalent to `p@@.x`.
* Switched for-loop back to returning pointers.
* This is an experiment; after implementing references, they do work well, but I dislike the huge amount of complexity added to the compiler. I want to see if I can use a similar strategy that Go uses; making pointers nicer to work with. I've also started to dislike the `@` syntax, and would prefer to use that for reflection like cppfront. I may end up going back to making derferencing a prefix operator, or using Zig style syntax `p.*` for dereferencing to disambiguate between that and multiplication.

Auto Dereference Pointers for Field Access

---

examples/feature_test.az
examples/list_destruction.az
examples/std/file.az
examples/std/string.az
examples/std/vector.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* `p.func()` is now valid when `p` is a pointer; it will dereference down to the original.
* Member functions now take pointers as their first args again. `assign` also takes `other` by pointer too.
* Added `node_member_call_expr` to the AST to implement member function calls in a more explicit way; parsing `x.foo(...)` as `typeof(x)::foo(x&, ...)` made it really hard to implement the dereferencing of the first arg in a non-hacky way.
* The new AST node also made it simpler to implement `.size()` on spans and this also fixes the bug of free functions called `size` getting picked in some cases.
* Also added `.size()` onto arrays as it was trivial to add.

Call Members Functions through Pointers

---

.vscode/settings.json
README.md
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/functions.cpp
src/lexer.cpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/token.cpp
src/token.hpp

* References made the code confusing and the compiler code hard to reason about.
* The main reason for implementing references in the first place was to make parameter passing nicer and being able to use simple dot syntax rather than `@.`.
* Since pointers cannot be null either, one of the other main differences between refs and pointers in C++ doesn't apply to Anzu.
* With the previous changes to allow for dot access on pointers, this mostly goes away. `@.` is still available but not really needed.
* Moved all the `concrete_X_type` and `is_X_type` functions to be member functions on `type_name`, similar to the const and pointer functions.
* `inner_type()` now only works for arrays and spans. For pointers and const, use `remove_ptr` and `remove_const` instead.
* Removed the `ref` keyword.

Remove References

---

.vscode/settings.json
examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp

* Rename `op::print_string_literal` to `op::print_char_span`, which now works for any kind of span, including the stack and heap.
* Allow for passing a `char[]` or `(const char)[]` to print is now valid.

Printing Char Spans

---

.vscode/launch.json
examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/utility/stack.hpp

* Store the rom as just a string. Remove vm_rom.
* Simplify the `read_advance` function usage.
* Fix function pointer usage, it broke at some point.
* Store `type_fundamental` directly as the enum in the variant, no need for wrapper function.
* Remove some old functions that are no longer used.

Runtime Cleanups

---

examples/test.az
examples/test_contents.txt
src/compiler.cpp
src/functions.cpp

* Add `fread` as a builtin function, making it possible to load file contents into a `(const char)[]`.
* Add `span_from_ptrs` builtin function which converts a pair of char pointers to a char span. This isn't safe but will be used to implement a tokeniser in the future. 
* Doing so highlighted some issues in the compiler; this makes is more robust (not perfect, just better), in particular, cleaning up all the type conversion code as most of the complexity still lingered from when functions could be overloaded. Now, conversions only relate to constness.
* Remove `verify_function_call` since it was a relic of function overloading.
* Remove `are_types_convertible_to` for the same reason.
* Remove `get_converter` which was already complicated logic. Arrays no longer auto convert to spans, …

Reading File Contents

---

src/compilation/variable_manager.cpp
src/compilation/variable_manager.hpp
src/utility/memory.hpp

* Made `scope` a simple struct; all the logic now lies fully inside the `variable_manager`, which makes some of the functions simpler.
* Remove all the private `push_X_scope` functions, the logic is now done entirely in the functions that return scope guards.
* Simplify the arena cleanup code, it's just one function now.

Simplify Variable Manager Again

---

examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/runtime.cpp
src/runtime.hpp

* We read into the program by using a `std::size_t` instruction pointer, this is now changed to an actual `std::byte*`. This is in prep for splitting the code into separate chunks of bytecode for each function.
* The `print_op` now no longer needs the whole program passed in, since it doesn't need to code vector to convert the instruction pointer to a pointer.
* Added a `op::end_program` op code to decide when to end the program rather than using the size of the program vector, as that vector is going away. Plus it also fixed an off-by-one bug with the new implementation.

Make the Instruction Pointer an Actual Pointer

---

.vscode/launch.json
examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compilation/variable_manager.cpp
src/compilation/variable_manager.hpp
src/compiler.cpp
src/compiler.hpp
src/runtime.cpp
src/runtime.hpp

* Major rewrite of the compiler and the runtime. Instead of compiling a program into a single vector of bytecode, we instead compile each function into a separate vector of bytecode and pass a vector of functions to the runtime.
* Each function has a unique ID, it's index in the vector. This ID is what gets used as a function pointer. On each call, the instruction pointer is just set to the first byte in the functions bytecode.
* The global scope is compiled as a function called `$main`, but it doesn't act like a function (unspellable name, has no signature, cannot use the return keyword, variables are global and accessible in other functions, automatically invoked etc).
* Fixed a whole load of issues surrounding members functions and constness. When pushing the first argument, we …

Compile Functions Individually

---

examples/test.az
src/anzu.m.cpp
src/compiler.cpp
src/compiler.hpp
src/parser.cpp
src/parser.hpp

* Modules were a half baked feature, and with the recent changes to the compiler and runtime, can likely be implemented in a smarter way, so they've been removed.
* "Debug" mode was always on and half baked, and implemented a bunch of checks in the language that added a load of extra op codes to the output. Removing it does make usage of some features more error prone, but that can be fixed in the future.
* Asserts now always fire, previously they were only enabled in debug mode.

Remove Modules and Debug Mode

---

examples/feature_test.az
examples/recursion.az
examples/test.az
src/compilation/type_manager.cpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* Remove `type_const` from the `type_name` variant, instead `type_name` just has an `is_const` bool stored directly on it.
* The bool doesn't count in the equality check, so `i64` would compare true to `i64 const`.
* This is because const only really matters for assignment, declaration and copying arguments into functions.
* Returns values from `push_expr_val` should have the top level const stripped away as it's up to the surrounding context if it should be const or not. For example, you should be able to use the value from a const variable to assign to a mutable variable since a copy is being made, but only top level const since a `u64 const&` should not be convertible to a `u64&`.
* Make `const` apply as a suffix, so `(const char)[]` is now spelled `char const[]` and `const (char[])` …

New Implementation of Const

---

.vscode/launch.json
examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compilation/type_manager.cpp
src/compilation/type_manager.hpp
src/compilation/variable_manager.cpp
src/compilation/variable_manager.hpp
src/compiler.cpp
src/compiler.hpp
src/object.cpp
src/object.hpp
src/parser.cpp

* Finally added template functions. The syntax is `fn foo|T|(args) { ... }`, using bars to denote the template list. I was originally going to do `<T>` like in C++, but that makes it much harder to parse and would require big changes to the lexer to allow going backwards through the token stream. Consider how would you parse `let x := foo < bar;`; as oppose to `let x := foo<bar>();` without requiring type information.
* When the compiler encounters the definition of a template function, it just stashes the AST for later. When a template function call appears, the compiler first compiles the function if it doesn't already exist and then the usual code for handling function calls works as normal (now that we use a fully qualified name everywhere).
* The `function_info` now contains a …

Template Functions

---

examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/compiler.hpp
src/parser.cpp

* Made it possible to have templated member functions.
* The implementation is largely the same as normal template functions; the compiler stashes the AST when it sees it and compiles it when needed.
* Generalises `node_member_call_expr` to be able to have multiple template types.

Template Member Functions

---

src/compiler.cpp

* Organize the compiler functions into 3 sections; helpers, expression compilers and statement compilers.
* Merge `push_expr_val` and `push_expr_ptr`.

Merge Expression Functions

---

examples/feature_test.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp

* Rather than having the template args on the call expression, they should instead be on whatever it is we're calling. This is a first step towards that.
* `node_call_expr` no longer accepts template arguments.
* Added `node_templated_name_expr`. This is similar to `node_name_expr` but contains a list of templates.
* When compiling a templated name expression, since it can only be a free function (for now), it first checks to see if it needs to compile the function, before returning a function pointer.
* Enables function pointers to template instantiations, eg `let f := func!(u64)` will stamp out a function and return a pointer to it.

Templated Named AST Node

---

examples/aoc2015-1.az
examples/feature_test.az
examples/test.az
examples/vector.az
src/compiler.cpp

* For loops now only operate on spans. Reason being; I disliked how the implementation was different depending on the arg being an lvalue or an rvalue (though I may bring this back in the future), because the impl to decide that was really bad and likely incorrect. Now, the container arg is always copied, which for arrays is likely always an error as it could be a huge copy, so is always disallowed.
* Made is possible to append `const` to a variable name, similarly to `&`. Only really useful for pointers and spans, but in particular for loops when you dont want to modify the underlying data. eg, if `x` is a `i64`, then `x const&` is a `i64 const&`, making it easy to explicitly create a pointer to const. To loop an array `arr` and make it read only, use `for x in arr const[] { ... }`.
* …

Reimplement For Loops

---

examples/vector.az
src/compiler.cpp
src/parser.cpp

* Fix a bug when calling a template free function from a template member function would result in the template type not being found. This is fixed by pushing the global namespace as the struct type when compiling a free function.
* It is no longer necessary to spell the type name out when writing a member function. Simply writing `&` or `const&` will do. This could be expanded further to allow for `[]` and `N` to mean a span or array of the given type, or empty to mean a value, but I'll do that when I need to.

Templates QOL

---

examples/test.az
examples/vector.az
src/ast.cpp
src/ast.hpp
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/lexer.cpp
src/parser.cpp
src/runtime.cpp
src/token.cpp
src/token.hpp

* Added the C ternary operator with the same syntax and operator precedence.
* Added another form of the new expression that takes a third argument which must be an existing span. The newly allocated span must be larger than it, and it copies the value of the span over, using the expr to fill in the remaining elements. The `new` expression is a bit of a mess now, a nicer syntax should be created.
* Both make implementing vector simpler, so it will help with maps too.
* I don't quite like the "realloc" use of new; the old array is still perfectly fine in memory given how arenas work, so really it is just an allocate + copy, so maybe a copy operation would be more appropriate to have. On the flip side, it would be easy to add an optimisation to see if the array to realloc was the last …

Ternary and Realloc

---

examples/tokenizer.az
examples/vector.az
src/compiler.cpp

* It is now possible to access member functions on structs directly through the struct itself. For example, given a object `vec` of type `vector!(u64)`, you can either call `vec.size()` or equivalently `vector!(u64).size(vec&)`.
* This allows for member functions that don't have a self parameter. Trying to call one of the these on a instance of a class is an error.
* To implement this, the check on the first argument to the function is now done in `node_field_expr` when constructing the bound method object, rather than in `compile_function`.
* The example functions `new_vector` and `new_tokenizer` are now spelled `vector.create` and `tokenizer.create`.
* With this, there's a bit more duplication in the handling of compiling templates, and it may be possible to generalise the current …

Static Methods

---

examples/module.az
examples/test.az
lib/tokenizer.az
src/compiler.cpp

* When compiling a sequence statement, a new scope is added, so a new scope was getting added when compiling a module, meaning all globals would be cleaned up after importing.
* This fix unwraps the top level sequence statement in a module and compiles each statement separately to avoid this.
* In the future, a cleaner impl would probably involve a module not having a top level sequence statement but instead just have a vector of statements.

Fix Variable Access from Modules

---

README.md
examples/feature_test.az
examples/module.az
examples/test.az
lib/io.az
lib/utility.az
lib/vector.az
src/CMakeLists.txt
src/compilation/type_manager.hpp
src/compilation/variable_manager.cpp
src/compilation/variable_manager.hpp
src/compiler.cpp
src/compiler.hpp
src/names.cpp
src/names.hpp
src/object.cpp
src/object.hpp

* Objects from other modules can now only be accessed as fields on the delcared module object, essentially namespacing the objects in them.
* Only global variables, (template) structs and (template) functions are exposed publicly from modules.
* You cannot access other modules though modules, so no transitivity at all.
* Major refactor of the compiler which is now much more maintainable.
* Factored out code for fetching functions and structs by name, and all template instantiation happens in there, so templates don't need to be reasoned about in the rest of the compiler.
* There are now proper "name" structs to act as keys for the template maps and struct maps, rather than stringifying everything, which was hard to maintain.
* `type_struct` is now used more heavily in places, and also …

Module Namespacing

---

README.md
examples/test.az
src/compiler.cpp

* Putting types into the expression system is actually way cooler than I expected.
* Removing some over-protective checks and making types assignable via implementing them properly in `const_convertible_to` allows you to define type aliases via the same syntax as variables, it `let Integer := i64`. Because type expressions are evaluated using the same expression logic, writing something like `Integer&` results in a pointer type, rather than a pointer to a variable, so it's a true alias.
* These are stored as variables in the compiler, but have a size of 0.
* Optimisation: all occurrence of `op::load` and `op::save` now only get added if the size is greater than 0, so variables of size 0 have no runtime effect.
* In treating modules as the same, if you write `let m := mod` where `mod` is a …

Type Aliases

---

examples/test.az
src/compilation/type_manager.cpp
src/compiler.cpp
src/object.cpp
src/object.hpp

* Added the equivalent of `std::true_type` and `std::false_type`.
* Made it possible to compare types in a binary operation with `==` and `!=`, which results in a compile time bool.
* If an if statement condition is a compile time bool, only the true branch is compiled and the condition and other branch are left out of the program.
* Use `push_copy_typechecked` for return values, and allow it to decay a compile time bool into a runtime bool, allowing for compile time bools to be used as the return values from functions returning bool.
* Future changes are needed to allow for compile time bools in all places where regular bools are.
* With this, the true and false literals can be classed as compile time bools, which they currently are not, but the main goal for this was the if statement …

Compile Time Booleans (Part 1)

---

anzu-lang/syntaxes/anzu.tmLanguage.json
examples/feature_test.az
examples/test.az
lib/str.az
lib/utility.az
src/ast.cpp
src/ast.hpp
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/lexer.cpp
src/parser.cpp
src/runtime.cpp
src/token.cpp
src/token.hpp

* Added a new set of functions prefixed with a `@`. This has nothing to do with the suffix `@` for dereference and may change in the future. The goal of this is to make it easier to add functions that access compiler internals without needing to add a new AST node every time.
* Added `@size_of` which replaces `sizeof`, which is no longer a keyword.
* Added `@type_of` which replaces `typeof`, which is no longer a keyword.
* Added `@copy` which replaces `utils.copy!`, for a more efficient way of copying the contents of one span into another. This uses a new op code, `op::memcpy` to perform it in a single copy.
* Added `@char_to_i64` which converts a char to an i64. This uses a new op code, `op::char_to_i64`. I'll make this more generic as some point to include all other safe fundamental …

Intrinsic Functions

---

README.md
examples/aoc2023-1.az
examples/feature_test.az
examples/module.az
examples/test.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/lexer.cpp
src/parser.cpp
src/token.cpp
src/token.hpp

* Added a new intrinsic function, `@import`, which acts similar to existing module statements.
* The type of a `@import(...)` call is a `type_module`.
* The module only gets compiled when the module is captured in a declaration statement. It cannot happen as part of the intrinsic function call, because if it gets called in a `type_of_expr` evaluation, the compiled module gets popped off and the compiler will never re-add it. This can either be fixed by changing how `type_of_expr` works or by how module importing works, but I've not come up with a good way in either case yet.
* When a circular dependency is detected, it is now printed.
* Updated the readme to mention intrinsic functions.

Treat Modules Like Variables

---

README.md
examples/module.az
examples/test.az
lib/str.az
src/compiler.cpp

* Previously, `@import` would just create a module object and not compile the module; that would only be done in the declaration statement, which was weird. My understanding for why this was broken was incorrect.
* The reason: when loading variables, the compiler pushes the pointer followed by an `op::load` call with the size of the type. But for size 0 objects, this load was removed as an "optimisation", leaving a nonsense pointer on top of the stack. Removing this "optimisation" fixes this. In the future, this can likely be improved by handling size 0 types differently when loading variables to avoid the absolutely useless pointer.
* This means you can call `@import` without assigning to a variable, which will execute the module and make it impossible to reference values in it, which …

Fix `@import`, Add `@type_name_of`

---

examples/feature_test.az
lib/vector.az
src/compiler.cpp

* `@type_of` works by compiling the given expression and then removing all bytecode instructions added from the program. This was implemented back when the program was a single vector of bytes and hasn't changed, and while it still mostly works, there's some rough edges.
* Calling `@type_of(@import("module_name"))` should return the module type, but if this is the first time this module is imported, the resetting logic removes any of the global variables within the module. Structs and functions are fine since functions are compiled into separate places and structs are purely state for the compiler, but any of the logic that affects `$main` needs to stay around.
* The quick fix for this is to only do the logic resetting if the type of the expression has a non-zero size. If the object is of …

Bugfix: `@type_of` on a Module

---

examples/feature_test.az
examples/test.az
lib/vector.az
src/ast.cpp
src/ast.hpp
src/compilation/type_manager.cpp
src/compiler.cpp
src/object.cpp
src/object.hpp
src/parser.cpp

* In order to have template type deduction, it must be possible to have the expression `foo()` where `foo` is a template, not a concrete function, which is currently not possible.
* Added `type_function`, a size 0 type category which stores all the info for a particular function. This can convert to the `function_ptr` type implicitly. This was mainly added for consistency with the rest of the size 0 types.
* Added `node_template_expr` to the AST. This just contains a template type list. Removed the template lists from `node_name_expr` and `node_field_expr`.
* Added `type_function_template`, a size 0 type category, representing a function template. Applying a template list to it returns a `type_function` object.
* Similarly, added `type_struct_template` and `type_bound_method_template`, …

Template Type Deduction Preparation

---

examples/test.az
src/ast.cpp
src/ast.hpp
src/compilation/type_manager.cpp
src/compiler.cpp
src/compiler.hpp
src/object.cpp
src/object.hpp

* It is now possible for function templates to be within a call expression. The template arguments will get deduced from the function arguments.
* Implemented by introducing `type_placeholder` to make it possible to have types containing the un-deduced names.
* Deduction only happens for functions for now, but should be easy to implement the same for template structs and bound methods.
* Removed the old `is_lvalue` and `is_value` functions which are unused and also really out of date and incorrect.
* The `current_placeholders` stack on the compiler almost certainly doesn't need to be a stack, because I don't think it's possible to start deducing one function half way through deducing another, but I've done it as a stack anyway just in case.

Function Template Argument Type Deduction

---

src/compiler.cpp
src/object.hpp

* Re-extract the `get_function` logic into a function again, this time with a hard failure if the function cannot be found rather than returning an optional.
* Remove the function that checks for duplicate names since it only half works anyway. We already cannot have two things of the same category (struct, variable. function etc) since they are stored in maps and we have errors for that.
* Other various bits of spring cleaning.

Template Deduction Cleanup

---

examples/test.az
src/compiler.cpp
src/object.cpp

* Another load of code duplication to allow for `type_bound_method_template` to be directly callable and infer template types from the arguments.
* Current implementation skips over the `self` parameter when doing template deduction, meaning it's not possible for `self` to be a template type, which in practice isn't a big deal. The only thing where this may be useful is to allow for C++ "Deducing this" style code where the template type can infer constness. I'll add it if I need it.
* The reason the self param is ignored is because it's just a bit fiddly; it may be cleaner to resolve the signature of a template function earlier on by making use of placeholders, but I'll experiment with that in the future.
* Turns out I have `std::ranges::to` available, so made a bit of use of that.

Template Deduction for Bound Methods

---

examples/test.az
src/compilation/type_manager.cpp
src/compilation/type_manager.hpp
src/compiler.cpp
src/compiler.hpp
src/object.cpp
src/object.hpp
src/utility/common.hpp

* Remove a lot of duplication in the code for `node_name_expr` and `node_template expr`.
* We only need to type check the first arg of bound method templates in `node_field_expr` where we do it for bound methods. No need to do it in `node_call_expr` and `node_template_expr`, simplfying it further.
* Remove `zip` and use `std::views::zip`.
* The type manager now only stores struct types. Can probably be removed and stored directly in the compiler at some point.
* Only store struct template values in the type manager; the current_struct stack only stores the name now.

Bound Method Deduction Cleanup

---

examples/aoc2023-1.az
src/compiler.cpp

* If we have a pointer `p` to an object of a type with a field `foo`, then `p.foo` is well-defined and is equivalent to `p@.foo`; ie- field access auto-dereferences through pointers. This now applies to subscripts.
* If you have a pointer `p` to an array or span, then `p[n]` is now equivalent to `p@[n]`.
* Now the only real time you *need* to explicitly dereference is if you need the value itself.

Subscript Auto-Dereference

---

src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/compiler.hpp
src/parser.cpp
src/runtime.cpp

* The runtime called `apply_op` in a loop which returned true or false to say whether the program should continue. This resulted in a boolean check on every op code!
* This PR removes that by putting the while loop and switch statement in the same function, and `op::end_program` just returns from the function rather than returning a bool.
* This resulted in the aoc2023 solution (in debug mode) to go from 1.8 seconds to 1.1 seconds!
* Also done a lot of smaller cleanup in the compiler; removing superfluous structs and simplifying.

Improve Performance by ~35%

---

examples/aoc2023-1.az
src/anzu.m.cpp
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/runtime.cpp

* The way values are loaded onto the stack is inefficient; currently we always push a pointer via `op::push_ptr_local` and `op::push_ptr_global` and then push a separate `op::load`. Added `op::push_val_local` and `op::push_val_global` to load directly in a single instruction. This brought aoc2023 in debug down from 1.1s to 1.02s.
* Added `op::nth_element_ptr` and `op::nth_element_val` which pops an index and a pointer from the stack, and stores a size statically, and pushes a pointer to / value of the element at the index, speeding up both subscripting and for loops, bringing aoc2023 down under a second.
* Added `op::call_static`; all places except for one where we use `op::call`, we know the function pointer statically, so the combination of `op::push_function_ptr` + `op::call` can be …

More Runtime Optimisations (~12% speedup)

---

examples/test.az
src/compiler.cpp

* It is now possible to instantiate instances of struct templates without explicitly declaring the template types.

Template Deduction for Structs

---

examples/test.az
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/runtime.cpp

* Added `op::span_ptr_to_len`, which pops a pointer to a span off the stack and pushes the length.
* Added `op::push_subspan` which pops a pointer to a span and upper and lower indices off the stack, and pushes a new span.
* Both of these improve the performance of `aoc2023-1.az` in debug from 0.95s to 0.75s since it makes a lot of calls into these code paths.
* Improve for loops very slightly by making use of `op::span_ptr_to_len` to get the length.

Improve Performance of Span Functionality

---

.vscode/settings.json
README.md
examples/feature_test.az
examples/test.az
lib/vector.az
src/ast.cpp
src/ast.hpp
src/compilation/type_manager.cpp
src/compiler.cpp
src/lexer.cpp
src/object.cpp
src/object.hpp
src/parser.cpp
src/token.cpp
src/token.hpp

* Removes `nullptr` as a keyword, just use `null` instead.
* `push_copy_typechecked` has been updated to allow for the conversions to null pointers and null spans.
* Binary operation compilation has been updated to allow for comparing pointers to `null`. Maybe should allow for comparison against spans for consistency, but spans can't currently be compared (but maybe they should be).

Replace `nullptr` with `null`

---

.vscode/settings.json
README.md
examples/feature_test.az
examples/test.az
lib/map.az
lib/str.az
lib/utility.az
lib/vector.az
src/ast.cpp
src/ast.hpp
src/bytecode.cpp
src/bytecode.hpp
src/compiler.cpp
src/lexer.cpp
src/parser.cpp
src/runtime.cpp
src/token.cpp
src/token.hpp

* A bunch of tools and improvements needed in order to implement a hash map. More are needed but this is a start.
* Added `<expr> as <type>` syntax, inspired by rust. Currently only `as i64` and `as u64` for fundamental types is implemented.
* Removed `@char_to_i64`.
* Added `@compare(lhs, rhs)` intrinsic which is a safe wrapper for `memcmp`.
* Added `@is_fundamental(type)` intrinsic which returns true if and only if the given type is a fundamental type. This along with the `as` statement makes implementing the standard hash function simpler.
* Implemented the compile time check `T == null` which was previously broken because `null` is itself its own type, so `T == null` would drop into the value comparison for null rather than type comparison. Maybe `null_type` should be included, but I …

Hash Map Setup

---

examples/test.az
src/compiler.cpp
src/object.cpp
src/object.hpp

* Using the new `const_value` mechanism, the `type_type` struct no longer contains type info.
* `@type_of(T)` is now just `type` for every type.
* Objects of type `type` must be known at compile time to be usable.
* The type of `type` is itself.
* Fixed the compile time bools which still need to push runtime code (but just a const value).

Single Type Type

---

examples/feature_test.az
examples/test.az
src/compilation/type_manager.cpp
src/compiler.cpp
src/functions.cpp
src/object.cpp
src/object.hpp

* Added helper functions to improve accessing values of types and modules.
* Removed `type_fundamental`, now all fundamental types are their own structs, which simplifies a lot of the code.
* Definition of `is_fundamental` is now `null`, `bool`, `char`, `i32`, `i64`, `u64` and `f64`, excluding `arena`, `type` and `module` which could also be considered fundamental, but have special behaviour.
* Removed all the trivial factory functions like `i64_type()` since you can just do `type_i64{}` now.

Remove `type_fundamental`

---

examples/test.az
lib/utility.az

* Wrap the initial call to quicksort so only the span needs to be passed in.
* Rename `quick_sort` to just `sort`.
* The original sort function is called `partial_sort`.

SImpler Quicksort

---

examples/test.az
lib/std.az
src/compiler.cpp
src/object.hpp
src/runtime.cpp
src/runtime.hpp

* Add `std.zip`, `std.enumerate` and `std.pairwise`.
* Rename `std.tokenizer` to `std.split_iterator` to make it consistent with the other iterators.
* Don't deallocate arenas, instead add them to a free-list so that can be reused. Unsure if this is a good idea but it makes using an arena in a hot loop performant.
* Found the issue that causes the bug of not being able to deduce template types within a template function; it's because the names of the placeholders overlap and need to be disambiguated. Will fix this in the next PR.

More Itertools

---

lib/std.az
src/compiler.cpp
src/object.cpp
src/object.hpp

* Anzu has a custom formatter that lets any type with a `.to_string()` be printable, but for the type structs I have `anzu::to_string` free functions instead.
* Made all of these free functions member functions instead.
* Removed some redundant wrapping of types in some prints.

All Types Printable

---

examples/feature_test.az
examples/test.az
lib/std.az
src/compiler.cpp
src/compiler.hpp

* Doing a template deduction within a template function was broken, but only if the two functions used the same name for the placeholder.
* This was due to two things; firstly, name lookup when compiling `node_name_expr` would check the current function and struct template parameters before checking the "current_placeholders", which is set during type deduction (naming here is bad I know). It should always check the current_placeholders first.
* Second, the current_placeholders should only be set when resolving the function params; not the arguments passed to the function. Otherwise, if both the caller and callee have a template placeholder with the same name (say `T`), then it sets the type of a variable passed in (which uses `T` from the caller) to `T` from the callee, which doesn't …

Fix Nested Template Deduction

---

README.md
examples/test.az
lib/std.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp

* Unpacking syntax has been expanded to nest to allow for nested unpacking: `let [a, [b, c]] := foo`.
* For for loops using iterators, you can now unpack the object: `for [index, value] in std.enumerate(...) {}`.
* Allows for a more convenient way to compose zip and enumerate: `for [index, [left, right]] in std.enumerate(std.zip(a, b)) {}`.
* Unpacking does not work for looping over spans since that returns pointers, maybe this needs to be changed?

Nested Unpacking and For Loop Use

---

README.md
examples/aoc2015-1.az
examples/aoc2023-1.az
examples/aoc2024-1.az
examples/feature_test.az
examples/test.az
lib/std.az
src/ast.cpp
src/ast.hpp
src/compiler.cpp
src/parser.cpp

* Span based for loops used to return pointers, now they return values.
* If you want a pointer, you ask for it with a `&`, eg: `for x& in span { ... }`.
* Removed `std.iterspan` and replaced with `std.valspan` and `std.ptrspan` to turn both kinds of loops into their iterator equivalents to make spans composable with iterators. I don't like this but can't think of a better way.

Make For Loops Return Copies

---

README.md
examples/test.az
src/bytecode.cpp
src/compilation/type_manager.cpp
src/compiler.cpp
src/object.cpp
src/object.hpp

* Now that we have `expr_result` which is capable of returning compile-time values, there's no need to have separate types for `function` and `function_ptr`; a function is just a `function_ptr` with a compile-time known value!
* In the call expression, if we know the id of the function, we can call it statically, otherwise we can push the id at runtime.
* The remaining type is the old `function_ptr`, but is now just called `function`.
* The `function` type now has the same behaviour at scalar types; treat it like a runtime value, with the calling optimisation as mentioned above.
* There is no longer a need to have special logic to convert a `function` to a `function_ptr` when pushing as an argument to a function call.
* There is now a nice symmetry in the template types; …

Merge function and function_ptr types
